repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: ["-L", "crate,crate's,padd,stati,nd"]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        args: ["--fix"]
  - repo: https://github.com/errata-ai/vale
    rev: v3.8.0
    hooks:
      - id: vale
  - repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
      - id: interrogate
        args: ["-v", "-i", "src", "-f", "100", "-M"]
        pass_filenames: false
