name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip

          # Project/runtime deps
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

          # Dev/test-only deps
          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          fi

          # If installable as a package, install it (prefer dev extras if present)
          if [ -f pyproject.toml ] || [ -f setup.py ] || [ -f setup.cfg ]; then
            pip install ".[dev]" || pip install .
          fi

          # Ensure pytest is available even if not listed above
          python - <<'PY'
          import importlib, subprocess, sys
          try:
              importlib.import_module("pytest")
          except Exception:
              subprocess.check_call([sys.executable, "-m", "pip", "install", "pytest"])
          PY

      - name: Run tests
        shell: bash
        run: |
          # If pytest-cov is available, emit coverage.xml; otherwise run plain pytest
          if python - <<'PY'
          import importlib, sys
          sys.exit(0 if importlib.util.find_spec("pytest_cov") else 1)
          PY
          then
            pytest -q --maxfail=1 --disable-warnings --cov --cov-report=xml
          else
            pytest -q --maxfail=1 --disable-warnings
          fi

      - name: Upload coverage (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.xml
          if-no-files-found: ignore
